
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.vista;

import biblioteca.entidades.BibliotecarioEn;
import biblioteca.entidades.EmpleadoEn;
import biblioteca.entidades.EstudianteEn;
import biblioteca.negocio.BibliotecarioNg;
import biblioteca.negocio.EmpleadoNg;
import biblioteca.negocio.EstudianteNg;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DIOMEDES GUERRA
 */
public class LoginV extends javax.swing.JFrame {

    
    public LoginV() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelTitulo = new javax.swing.JLabel();
        JlabelIconoLogin = new javax.swing.JLabel();
        JbuttonSalir = new javax.swing.JButton();
        JbuttonEntrar = new javax.swing.JButton();
        JlabelUser = new javax.swing.JLabel();
        JlabelContraseña = new javax.swing.JLabel();
        JtextUser = new javax.swing.JTextField();
        JpassContraseña = new javax.swing.JPasswordField();
        jButtonRegresarPrincipal = new javax.swing.JButton();
        jComboBoxTipoUser = new javax.swing.JComboBox<>();
        JlabelFondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        JlabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JlabelTitulo.setForeground(new java.awt.Color(0, 0, 102));
        JlabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabelTitulo.setText("INICIAR SESIÓN");
        getContentPane().add(JlabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 370, 30));

        JlabelIconoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONO LOGIN2.png"))); // NOI18N
        getContentPane().add(JlabelIconoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 220));

        JbuttonSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JbuttonSalir.setForeground(new java.awt.Color(255, 255, 255));
        JbuttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR-ICONO.png"))); // NOI18N
        JbuttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(JbuttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 40, 40));

        JbuttonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/INICIO-SESION-ICONO.png"))); // NOI18N
        JbuttonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbuttonEntrarMouseClicked(evt);
            }
        });
        JbuttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(JbuttonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 40, 70));

        JlabelUser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JlabelUser.setForeground(new java.awt.Color(0, 0, 153));
        JlabelUser.setText("USUARIO: *");
        getContentPane().add(JlabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, -1));

        JlabelContraseña.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JlabelContraseña.setForeground(new java.awt.Color(0, 0, 153));
        JlabelContraseña.setText("CONTRASEÑA: *");
        getContentPane().add(JlabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        JtextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextUserActionPerformed(evt);
            }
        });
        getContentPane().add(JtextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 160, 29));

        JpassContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpassContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(JpassContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 160, 28));

        jButtonRegresarPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HOME.ICONO.png"))); // NOI18N
        jButtonRegresarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 40, 40));

        jComboBoxTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Usuario", "Estudiante", "Empleado", "Bibliotecario" }));
        jComboBoxTipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUserActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        JlabelFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WALLPAPER BLANCO BIBLIOTECARIO.jpg"))); // NOI18N
        getContentPane().add(JlabelFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //VARIABLE QUE RECIBE EL TEXTO QUE CONTIENEN LOS COMBO BOX
String select;
//VALIDA QUE EL USUARIO SELECCIONE UN TIPO DE USUARIO
  public boolean ValidarOpcionTipoUser(){
      boolean opcionValidada;
     select=jComboBoxTipoUser.getSelectedItem().toString().trim();
       if(select.equalsIgnoreCase("Seleccionar Usuario")){
           JOptionPane.showMessageDialog(rootPane, "Seleccione un tipo de usuario Valido","Error",JOptionPane.ERROR_MESSAGE);
          opcionValidada= false;
      }else{
           opcionValidada=true;
           }
       return opcionValidada;
  }
  
     boolean estadoV=false,estado=false;
  
     
     //BOTON PARA ENTRAR O INICIAR SESION
    private void JbuttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonEntrarActionPerformed
       if(ValidarOpcionTipoUser()==true){
        String u, c = null;
        validacion();
            if (estado != false) {
                u = JtextUser.getText().trim();
                if(select.equalsIgnoreCase("bibliotecario")){
                    OpcionBibliotecario(u, c);
                            }
                if(select.equalsIgnoreCase("estudiante")){
                    OpcionEstudiante(u, c);
                } 
                
               if(select.equalsIgnoreCase("Empleado")){
                    OpcionEmpleado(u, c);
                } 
            }
       } 
           
    }//GEN-LAST:event_JbuttonEntrarActionPerformed
 
//USUARIO SELECCIONO LOGIN EMPLEADO
    public void OpcionEmpleado(String  u,String c){
        
        EmpleadoNg empleadoNg=new EmpleadoNg();
                List<EmpleadoEn> listaEmpleado = new ArrayList<EmpleadoEn>();
               listaEmpleado=empleadoNg.BuscarUsuarioLogin(u);
                if (!(listaEmpleado.isEmpty())) {
                    c =JpassContraseña.getText().trim();
                    ValidarUusarioContraseñaEmpleado(listaEmpleado, empleadoNg, u, c);
                    if (estadoV == true) {
                      JOptionPane.showMessageDialog(rootPane, "Inicio sesión correctamente", "Inicio de sesión", JOptionPane.INFORMATION_MESSAGE);
                       empleadoNg.EmpleadoLogin(empleadoNg.ObjetoEmpleado(u));  
                      clienteV.setVisible(true);
                        this.dispose();//invisibiliza una intefaz
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuario i/o contraseña incorrectos", "Error de inicio de sesion", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Este usuario no existe", "Inaexistencia", JOptionPane.ERROR_MESSAGE);
                }
}

//VALIDA EL USUARIO Y CONTRASEÑA DEL EMPLEADO
    public void ValidarUusarioContraseñaEmpleado(List<EmpleadoEn> listaEmpleado,EmpleadoNg empleadoNg,String u,String c){
          if (estadoV == false) {
                        Iterator<EmpleadoEn> iterador = listaEmpleado.iterator();
                        estadoV = empleadoNg.ValidarUCEmpleado(iterador, listaEmpleado, u, c);
                    }
    }

    //CREA UNA INSTANCIA O OBJETO DE LA VISTA DEL CLIENTE
ClientesV clienteV=new ClientesV();


//USUARIO SELECCIONO LOGIN ESTUDIANTE, TIPO DE USUARIO="ESTUDIANTE"
List<EstudianteEn> listaEstudiante = new ArrayList<EstudianteEn>();
    public void OpcionEstudiante(String  u,String c){
        
        EstudianteNg estudianteNg=new EstudianteNg();
               listaEstudiante=estudianteNg.BuscarUsuarioLogin(u);
                if (!(listaEstudiante.isEmpty())) {
                    c =JpassContraseña.getText().trim();
                    ValidarUusarioContraseñaEstudiante(listaEstudiante, estudianteNg,u,c);
                    if (estadoV == true) {
                        JOptionPane.showMessageDialog(rootPane, "Inicio sesión correctamente", "Inicio de sesión", JOptionPane.INFORMATION_MESSAGE);
                        estudianteNg.EstudianteLogin(estudianteNg.ObjetoEstudiante(u));
                        clienteV.setVisible(true);
                        this.dispose();//invisibiliza una intefaz
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuario i/o contraseña incorrectos", "Error de inicio de sesion", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Este usuario no existe", "Inaexistencia", JOptionPane.ERROR_MESSAGE);
                }
}
    
    //VALIDA EL USUARIO Y CONTRASEÑA DEL ESTUDIANTE
    public void ValidarUusarioContraseñaEstudiante(List<EstudianteEn> listaEstudiante,EstudianteNg estudianteNg,String u,String c){
          if (estadoV == false) {
                        Iterator<EstudianteEn> iteradoro = listaEstudiante.iterator();
                        estadoV = estudianteNg.ValidarUCEstudiante(iteradoro, listaEstudiante, u, c);
                                }
        }
      

//USUARIO SELECCIONO LOGIN BIBLIOTECARIO
    public void OpcionBibliotecario(String  u,String c){
     BibliotecarioNg biblioNg = new BibliotecarioNg();
                List<BibliotecarioEn> listaBiblio = new ArrayList<BibliotecarioEn>();
                listaBiblio=biblioNg.FindRegisters(u);
                if (!(listaBiblio.isEmpty())) {
                    c =JpassContraseña.getText().trim();
                  if(estadoV == false) {
                        Iterator<BibliotecarioEn> iteradoro = listaBiblio.iterator();
                        estadoV = biblioNg.ValidarUC(iteradoro, listaBiblio, u, c);
                                       }
                    if (estadoV == true) {
                        JOptionPane.showMessageDialog(rootPane, "Inicio sesión correctamente", "Inicio de sesión", JOptionPane.INFORMATION_MESSAGE);
                        BibliotecarioV biblioV=new BibliotecarioV();
                        biblioV.setVisible(true);
                        this.dispose();//invisibiliza una intefaz
                                         } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuario i/o contraseña incorrectos", "Error de inicio de sesion", JOptionPane.ERROR_MESSAGE);
                                                }
                                                } else {
                    JOptionPane.showMessageDialog(rootPane, "Este usuario no existe", "Inaexistencia", JOptionPane.ERROR_MESSAGE);
                                                       }
}
    
    
    
       public void validacion() {

        if (!(JtextUser.getText().equals("") || JpassContraseña.getText().trim().equals(""))) {
            estado = true;
                                 }
        if (estado == false) {
            JOptionPane.showMessageDialog(rootPane, "Campo vacío", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                                }
    }
    private void JbuttonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbuttonEntrarMouseClicked
     
    }//GEN-LAST:event_JbuttonEntrarMouseClicked

    private void JbuttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonSalirActionPerformed
        //CIERRA SOLO UNA VENTANA
        dispose();
        //CIERRA TODAS LAS VENTANAS
        //System.exit(0);
    }//GEN-LAST:event_JbuttonSalirActionPerformed

    private void JtextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextUserActionPerformed

    private void JpassContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpassContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpassContraseñaActionPerformed

    private void jComboBoxTipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoUserActionPerformed

    private void jButtonRegresarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarPrincipalActionPerformed
       UsuariosV userV=new UsuariosV();
        userV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonEntrar;
    private javax.swing.JButton JbuttonSalir;
    private javax.swing.JLabel JlabelContraseña;
    private javax.swing.JLabel JlabelFondoLogin;
    private javax.swing.JLabel JlabelIconoLogin;
    private javax.swing.JLabel JlabelTitulo;
    private javax.swing.JLabel JlabelUser;
    private javax.swing.JPasswordField JpassContraseña;
    private javax.swing.JTextField JtextUser;
    private javax.swing.JButton jButtonRegresarPrincipal;
    private javax.swing.JComboBox<String> jComboBoxTipoUser;
    // End of variables declaration//GEN-END:variables
}
