package biblioteca.vista;

import biblioteca.entidades.BibliotecarioEn;
import biblioteca.entidades.LibroEn;
import biblioteca.negocio.LibroNg;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIOMEDES GUERRA
 */
public class UsuariosV extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosV
     */
    public UsuariosV() {
        initComponents();
        //CENTRA LA VENTANA
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoBusqueda = new javax.swing.JComboBox<>();
        BuscarUser = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        JlabelTituloPagina = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibros = new javax.swing.JTable();
        JbuttonSalir = new javax.swing.JButton();
        JbuttonInicioSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoBusqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TITULO", "AUTOR" }));
        TipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(TipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, -1));

        BuscarUser.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        BuscarUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUserActionPerformed(evt);
            }
        });
        BuscarUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarUserKeyTyped(evt);
            }
        });
        getContentPane().add(BuscarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 610, 40));

        BuscarButton.setBackground(new java.awt.Color(204, 204, 204));
        BuscarButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        BuscarButton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR-ICONO.png"))); // NOI18N
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 40, 40));

        JlabelTituloPagina.setBackground(new java.awt.Color(255, 255, 255));
        JlabelTituloPagina.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JlabelTituloPagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabelTituloPagina.setText("BUSQUEDA MATERIAL BIBLIOGRAFICO");
        getContentPane().add(JlabelTituloPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 660, 30));

        jTableLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLibros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 670, 118));

        JbuttonSalir.setBackground(new java.awt.Color(204, 204, 204));
        JbuttonSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JbuttonSalir.setForeground(new java.awt.Color(255, 255, 255));
        JbuttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR-ICONO.png"))); // NOI18N
        JbuttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(JbuttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, -1));

        JbuttonInicioSesion.setBackground(new java.awt.Color(204, 204, 204));
        JbuttonInicioSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JbuttonInicioSesion.setText("INICIO SESIÓN");
        JbuttonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(JbuttonInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 9, -1, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WALLPAPER BLANCO BIBLIOTECARIO.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    TableRowSorter trs;
    private void BuscarUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarUserKeyTyped
   
        BuscarUser.addKeyListener(new KeyAdapter(){
        
            public void KeyReleased(KeyEvent ke){
            
                trs.setRowFilter(RowFilter.regexFilter(BuscarUser.getText(), 2));
            }
        });
        trs= new TableRowSorter(mtabla);
        jTableLibros.setRowSorter(trs);
    }//GEN-LAST:event_BuscarUserKeyTyped

    private void BuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUserActionPerformed
    
    }//GEN-LAST:event_BuscarUserActionPerformed

    
boolean valido=false;
String cadena;
//VACIA LA TABLA DESPUES DE CADA BUSQUEDA
 public void remover(){
       int filas=jTableLibros.getRowCount();
         for (int i = filas-1; i >=0; i--) {
             mtabla.removeRow(i);
         }
    } 
 int swLimpiar=0;
    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
      if (swLimpiar==1)
      {
          remover();
      }

//Validar que los campos no esten vacios
       Validaciones();
       int j;
       j=OpcionSeleccionada();
       if(valido==true){
         String titulo;
         String autor;
         titulo=BuscarUser.getText().trim();
         autor=BuscarUser.getText().trim();
         LibroNg librong=new LibroNg();
         List<LibroEn> listaLibro = new ArrayList<LibroEn>();
         listaLibro=librong.CargarRegistros(titulo, autor,j);
         if(listaLibro.isEmpty()==false){
             cargarModelo(listaLibro);
              swLimpiar=1;
         }else{
             JOptionPane.showMessageDialog(rootPane,cadena+" no encontrado","Error de busqueda",JOptionPane.ERROR_MESSAGE);
         }    
            
       }
      
    }//GEN-LAST:event_BuscarButtonActionPerformed

    
    public int OpcionSeleccionada(){
        int j;
         String funcion= TipoBusqueda.getSelectedItem().toString().trim();
        if(funcion.equalsIgnoreCase("TITULO")){
           cadena= "Titulo";
           return 1;
        }else{
            cadena="Autor";
            return 0;
        }
    }
    
  public void cargarModelo(List<LibroEn> listaLibros){
    
        for(LibroEn li: listaLibros){
           mtabla.addRow(new Object[]{li.getNombreLibro(),li.getAutor(),li.getCodigoLibro(),li.getEstadoLibro()} ); 
        }
        jTableLibros.setModel(mtabla);
     
       
    }  
    
    
    

    public void Validaciones(){
          if (BuscarUser.getText().length()!=0) {
            valido = true;
        }//validacion de el select
        if (valido == false) {
            JOptionPane.showMessageDialog(rootPane, "No selecciono uno de los campos verifique y vuelvalo a intentar", "ERROR 365", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void TipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBusquedaActionPerformed


    
    //GENERA MATRIZ
     String []encabezados={"Titulo","Autor","Código","Estado"};
    Object[][] filas=null;
    DefaultTableModel mtabla=new DefaultTableModel(filas,encabezados);
    
    
    
    private void jTableLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLibrosMouseClicked

    private void JbuttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonSalirActionPerformed
       //CIERRA SOLO UNA VENTANA
        System.exit(0);
    }//GEN-LAST:event_JbuttonSalirActionPerformed


//OBJECTO DE LA CLASE LOGIN
    LoginV bV=new LoginV();

    private void JbuttonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonInicioSesionActionPerformed
       //LLEVAR HASTA LA INTERFAS DEL LOGIN
       bV.setVisible(true);
       dispose();
    }//GEN-LAST:event_JbuttonInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField BuscarUser;
    private javax.swing.JButton JbuttonInicioSesion;
    private javax.swing.JButton JbuttonSalir;
    private javax.swing.JLabel JlabelTituloPagina;
    private javax.swing.JComboBox<String> TipoBusqueda;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibros;
    // End of variables declaration//GEN-END:variables

    
}
